//! HTTP side: the `/ws` WebSocket endpoint and the static web UI.

use std::path::PathBuf;
use std::sync::Arc;

use axum::extract::ws::{Message, Utf8Bytes, WebSocket, WebSocketUpgrade};
use axum::extract::{Request, State};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::Router;
use gs_protocol::CommandKind;
use tokio::sync::broadcast::error::RecvError;
use tokio::sync::{mpsc, oneshot};
use tower::ServiceExt;
use tower_http::services::{ServeDir, ServeFile};
use tracing::debug;

use crate::hub::Hub;
use crate::live::LinkRequest;
use crate::messages::{ClientMessage, ServerMessage};
use crate::routing::{Endpoints, RoutedCommand};

const UI_NOT_BUILT: &str = "gs-bridge is running, but the web UI has not been built.\n\
    Run `npm install && npm run build` in web/ (or pass --web-dir), then reload.\n\
    The WebSocket API is available at /ws.\n";

#[derive(Clone)]
pub struct AppState {
    pub hub: Arc<Hub>,
    /// `None` in replay mode, where there is nothing to command or record.
    pub link: Option<LinkHandle>,
    pub web_dir: PathBuf,
}

/// Where browser messages go: the routing table and the queue into the link task.
#[derive(Clone)]
pub struct LinkHandle {
    pub endpoints: Endpoints,
    pub tx: mpsc::Sender<LinkRequest>,
}

pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/ws", get(ws_upgrade))
        .fallback(static_files)
        .with_state(state)
}

/// Serves the built UI with a fallback to `index.html` so client-side routes work.
/// The directory is checked per request, so building the UI needs no bridge restart.
async fn static_files(State(state): State<AppState>, request: Request) -> Response {
    let index = state.web_dir.join("index.html");
    if !index.is_file() {
        return UI_NOT_BUILT.into_response();
    }
    let service = ServeDir::new(&state.web_dir).fallback(ServeFile::new(index));
    match service.oneshot(request).await {
        Ok(response) => response.into_response(),
        Err(never) => match never {},
    }
}

async fn ws_upgrade(State(state): State<AppState>, upgrade: WebSocketUpgrade) -> Response {
    upgrade.on_upgrade(move |socket| client_session(socket, state))
}

async fn client_session(mut socket: WebSocket, state: AppState) {
    let (snapshot, mut live) = state.hub.join();
    debug!("WebSocket client connected");
    for message in snapshot {
        if socket.send(Message::Text(message)).await.is_err() {
            return;
        }
    }

    loop {
        tokio::select! {
            broadcast = live.recv() => match broadcast {
                Ok(message) => {
                    if socket.send(Message::Text(message)).await.is_err() {
                        break;
                    }
                }
                // This client fell behind; it skips the missed telemetry and carries on.
                Err(RecvError::Lagged(_)) => {}
                Err(RecvError::Closed) => break,
            },
            incoming = socket.recv() => match incoming {
                Some(Ok(Message::Text(text))) => {
                    if let Err(message) = handle_client_text(&text, &state).await {
                        let reply = Utf8Bytes::from(ServerMessage::error(message).to_json());
                        if socket.send(Message::Text(reply)).await.is_err() {
                            break;
                        }
                    }
                }
                Some(Ok(Message::Close(_))) | Some(Err(_)) | None => break,
                // Pings are answered by axum; binary frames are not part of the API.
                Some(Ok(_)) => {}
            },
        }
    }
    debug!("WebSocket client disconnected");
}

/// Handles one browser message: a command is routed and queued for the UDP link, a
/// control message is answered by the link task. The error string goes back to that
/// client only.
async fn handle_client_text(text: &str, state: &AppState) -> Result<(), String> {
    let message = ClientMessage::parse(text)?;
    let Some(link) = &state.link else {
        return Err("replay mode: commands and recording controls are ignored".into());
    };
    const LINK_DOWN: &str = "the UDP link is not running";
    match message {
        ClientMessage::Command(kind) => {
            if kind == CommandKind::Heartbeat {
                return Err("heartbeats are generated by the bridge".into());
            }
            let endpoint = link.endpoints.route(&kind).map_err(str::to_string)?;
            link.tx
                .send(LinkRequest::Command(RoutedCommand { endpoint, kind }))
                .await
                .map_err(|_| LINK_DOWN.to_string())
        }
        ClientMessage::Control(control) => {
            let (reply, answer) = oneshot::channel();
            link.tx
                .send(LinkRequest::Control { control, reply })
                .await
                .map_err(|_| LINK_DOWN.to_string())?;
            answer.await.map_err(|_| LINK_DOWN.to_string())?
        }
    }
}
